### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by shiv71** [cometchat/cometchat-uikit-android#8]
In the Add UI kit library hyper link not working 

Simply clone the project from [android-java-chat-ui-kit](https://github.com/cometchat-pro-samples/android-java-chat-uikit/) repository.

Import uikit Module from Module Settings.( To know how to import uikit as Module visit this [link](https://prodocs.cometchat.com/v2.1/docs/android-ui-kit-setup) )

**Comment by ketanyekale** [comment]
This has been fixed. Please try the latest version of the UI Kit.
